export const data = [
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/pdfCr8W0wBCpdjbZXSxnKhZtosP.jpg",
        id: 84773,
        name: "The Lord of the Rings: The Rings of Power",
        original_language: "en",
        original_name: "The Lord of the Rings: The Rings of Power",
        overview:
          "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
        poster_path: "/suyNxglk17Cpk8rCM2kZgqKdftk.jpg",
        media_type: "tv",
        genre_ids: [10765, 10759, 18],
        popularity: 6145.327,
        first_air_date: "2022-09-01",
        vote_average: 7.527,
        vote_count: 386,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
        id: 361743,
        title: "Top Gun: Maverick",
        original_language: "en",
        original_title: "Top Gun: Maverick",
        overview:
          "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
        poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        media_type: "movie",
        genre_ids: [28, 18],
        popularity: 2029.875,
        release_date: "2022-05-24",
        video: false,
        vote_average: 8.355,
        vote_count: 3515,
      },
      {
        adult: false,
        backdrop_path: "/Aa9TLpNpBMyRkD8sPJ7ACKLjt0l.jpg",
        id: 94997,
        name: "House of the Dragon",
        original_language: "en",
        original_name: "House of the Dragon",
        overview:
          "The prequel series finds the Targaryen dynasty at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires—real and imagined—crumble from such heights. In the case of the Targaryens, their slow fall begins almost 193 years before the events of Game of Thrones, when King Viserys Targaryen breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
        poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
        media_type: "tv",
        genre_ids: [18, 10759, 10765, 9648],
        popularity: 6455.182,
        first_air_date: "2022-08-21",
        vote_average: 8.683,
        vote_count: 950,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
        id: 616037,
        title: "Thor: Love and Thunder",
        original_language: "en",
        original_title: "Thor: Love and Thunder",
        overview:
          "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
        poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
        media_type: "movie",
        genre_ids: [28, 12, 14],
        popularity: 4237.659,
        release_date: "2022-07-06",
        video: false,
        vote_average: 6.793,
        vote_count: 2397,
      },
      {
        adult: false,
        backdrop_path: "/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg",
        id: 762504,
        title: "Nope",
        original_language: "en",
        original_title: "Nope",
        overview:
          "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
        poster_path: "/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
        media_type: "movie",
        genre_ids: [27, 9648, 878, 53],
        popularity: 2087.208,
        release_date: "2022-07-20",
        video: false,
        vote_average: 7.065,
        vote_count: 1265,
      },
      {
        adult: false,
        backdrop_path: "/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg",
        id: 629176,
        title: "Samaritan",
        original_language: "en",
        original_title: "Samaritan",
        overview:
          "Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.",
        poster_path: "/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg",
        media_type: "movie",
        genre_ids: [28, 18, 878],
        popularity: 5115.365,
        release_date: "2022-08-25",
        video: false,
        vote_average: 7.031,
        vote_count: 827,
      },
      {
        adult: false,
        backdrop_path: "/9GvhICFMiRQA82vS6ydkXxeEkrd.jpg",
        id: 92783,
        name: "She-Hulk: Attorney at Law",
        original_language: "en",
        original_name: "She-Hulk: Attorney at Law",
        overview:
          "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
        poster_path: "/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg",
        media_type: "tv",
        genre_ids: [35, 10765],
        popularity: 6259.555,
        first_air_date: "2022-08-18",
        vote_average: 7.328,
        vote_count: 611,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/1DBDwevWS8OhiT3wqqlW7KGPd6m.jpg",
        id: 985939,
        title: "Fall",
        original_language: "en",
        original_title: "Fall",
        overview:
          "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.",
        poster_path: "/v28T5F1IygM8vXWZIycfNEm3xcL.jpg",
        media_type: "movie",
        genre_ids: [53],
        popularity: 2453.108,
        release_date: "2022-08-11",
        video: false,
        vote_average: 7.447,
        vote_count: 219,
      },
      {
        adult: false,
        backdrop_path: "/jauI01vUIkPA0xVsamGj0Gs1nNL.jpg",
        id: 507086,
        title: "Jurassic World Dominion",
        original_language: "en",
        original_title: "Jurassic World Dominion",
        overview:
          "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
        poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
        media_type: "movie",
        genre_ids: [12, 28, 878],
        popularity: 2083.754,
        release_date: "2022-06-01",
        video: false,
        vote_average: 7.1,
        vote_count: 3222,
      },
      {
        adult: false,
        backdrop_path: "/xfNHRI2f5kHGvogxLd0C5sB90L7.jpg",
        id: 539681,
        title: "DC League of Super-Pets",
        original_language: "en",
        original_title: "DC League of Super-Pets",
        overview:
          "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
        poster_path: "/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
        media_type: "movie",
        genre_ids: [16, 28, 10751, 878, 35],
        popularity: 2738.291,
        release_date: "2022-07-27",
        video: false,
        vote_average: 7.59,
        vote_count: 437,
      },
      {
        adult: false,
        backdrop_path: "/7Y3LdmsZukXhmwxtO0UF95BFBTt.jpg",
        id: 682507,
        title: "Where the Crawdads Sing",
        original_language: "en",
        original_title: "Where the Crawdads Sing",
        overview:
          "Abandoned by her family, Kya raises herself all alone in the marshes outside of her small town. When her former boyfriend is found dead, Kya is instantly branded by the local townspeople and law enforcement as the prime suspect for his murder.",
        poster_path: "/n1el846gLDXfhOvrRCsyvaAOQWv.jpg",
        media_type: "movie",
        genre_ids: [18, 9648],
        popularity: 250.974,
        release_date: "2022-07-15",
        video: false,
        vote_average: 7.382,
        vote_count: 144,
      },
      {
        adult: false,
        backdrop_path: "/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
        id: 766507,
        title: "Prey",
        original_language: "en",
        original_title: "Prey",
        overview:
          "When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.",
        poster_path: "/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
        media_type: "movie",
        genre_ids: [53, 28],
        popularity: 2818.224,
        release_date: "2022-08-02",
        video: false,
        vote_average: 7.979,
        vote_count: 3656,
      },
      {
        adult: false,
        backdrop_path: "/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg",
        id: 532639,
        title: "Pinocchio",
        original_language: "en",
        original_title: "Pinocchio",
        overview:
          'A live action and CGI retelling of the beloved tale of a wooden puppet who embarks on a thrilling adventure to become a real boy. Other characters include Geppetto, the woodcarver who builds and treats Pinocchio as if he were his real son; Jiminy Cricket, who serves as Pinocchio’s guide as well as his "conscience"; the Blue Fairy; "Honest" John; Sofia the Seagull and The Coachman.',
        poster_path: "/h32gl4a3QxQWNiNaR4Fc1uvLBkV.jpg",
        media_type: "movie",
        genre_ids: [14, 12, 10751],
        popularity: 349.131,
        release_date: "2022-09-07",
        video: false,
        vote_average: 7.711,
        vote_count: 19,
      },
      {
        adult: false,
        backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
        id: 438148,
        title: "Minions: The Rise of Gru",
        original_language: "en",
        original_title: "Minions: The Rise of Gru",
        overview:
          "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
        poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
        media_type: "movie",
        genre_ids: [16, 12, 35, 14],
        popularity: 1769.796,
        release_date: "2022-06-29",
        video: false,
        vote_average: 7.67,
        vote_count: 1855,
      },
      {
        adult: false,
        backdrop_path: "/xyS0NgcQ2pbGWcwvSSu3xKEBhoO.jpg",
        id: 614934,
        title: "Elvis",
        original_language: "en",
        original_title: "Elvis",
        overview:
          "The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.",
        poster_path: "/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg",
        media_type: "movie",
        genre_ids: [10402, 18, 36],
        popularity: 547.598,
        release_date: "2022-06-22",
        video: false,
        vote_average: 7.883,
        vote_count: 1369,
      },
      {
        adult: false,
        backdrop_path: "/14wIOjYCtfbO9EHTqCbiU9wncMz.jpg",
        id: 852448,
        title: "I Came By",
        original_language: "en",
        original_title: "I Came By",
        overview:
          "A rebellious young graffiti artist, who targets the homes of the wealthy elite, discovers a shocking secret that leads him on a journey endangering himself and those closest to him.",
        poster_path: "/856bLLUvEYu3dRDXCCoRE7oxO0V.jpg",
        media_type: "movie",
        genre_ids: [53],
        popularity: 176.96,
        release_date: "2022-08-19",
        video: false,
        vote_average: 6.105,
        vote_count: 129,
      },
      {
        adult: false,
        backdrop_path: "/5FFpcmPzD5mhLom7bymZq7Py8eT.jpg",
        id: 862551,
        title: "Me Time",
        original_language: "en",
        original_title: "Me Time",
        overview:
          "With his family away, a devoted stay-at-home dad enjoys his first me time in years by joining his hard-partying old friend on a wild birthday adventure.",
        poster_path: "/bkjPoisqAavXUvtoirxTEcLLQyI.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 1058.233,
        release_date: "2022-08-26",
        video: false,
        vote_average: 5.745,
        vote_count: 253,
      },
      {
        adult: false,
        backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
        id: 60625,
        name: "Rick and Morty",
        original_language: "en",
        original_name: "Rick and Morty",
        overview:
          "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
        poster_path: "/sGVCWtLG37mLOhl11qQVrjKsDzx.jpg",
        media_type: "tv",
        genre_ids: [16, 35, 10765, 10759],
        popularity: 1566.773,
        first_air_date: "2013-12-02",
        vote_average: 8.748,
        vote_count: 6848,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
        id: 634649,
        title: "Spider-Man: No Way Home",
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview:
          "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        poster_path: "/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
        media_type: "movie",
        genre_ids: [28, 12, 878],
        popularity: 1141.93,
        release_date: "2021-12-15",
        video: false,
        vote_average: 8.043,
        vote_count: 15007,
      },
      {
        adult: false,
        backdrop_path: "/2k9tBql5GYH328Krj66tDT9LtFZ.jpg",
        id: 760741,
        title: "Beast",
        original_language: "en",
        original_title: "Beast",
        overview:
          "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
        poster_path: "/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg",
        media_type: "movie",
        genre_ids: [53, 27],
        popularity: 479.698,
        release_date: "2022-08-11",
        video: false,
        vote_average: 6.421,
        vote_count: 89,
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
];
